name: Sync with upstream

on:
  schedule:
    - cron: "0 * * * *"  # Run every hour; adjust as needed
  push:
    branches:
      - main  # Run on push to the main branch
  pull_request:
    branches:
      - main  # Run on pull request targeting the main branch

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name 'Jaison'
        git config --global user.email 'jaison4577@gmail.com'

    - name: Add upstream remote
      run: git remote add upstream https://github.com/karankumarsahu/wireguard_server_test.git

    - name: Fetch upstream changes
      run: git fetch upstream

    - name: Checkout main.go from upstream
      run: |
        git checkout upstream/main -- main.go

    - name: Check if main.go has changes
      run: |
        git diff --quiet main.go || echo "Changes detected in main.go" > changes_detected.txt

    - name: Stage and commit changes to main.go
      run: |
        if [ -f changes_detected.txt ]; then
          git add main.go
          git commit -m "Sync main.go with upstream"
        else
          echo "No changes in main.go. Skipping commit."
        fi

    - name: Push changes to fork (if changes were made)
      run: |
        if [ -f changes_detected.txt ]; then
          git push origin main
        else
          echo "No changes to push."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
