name: Sync with upstream

on:
  schedule:
    - cron: "0 * * * *"  # Run every hour; adjust as needed
  push:
    branches:
      - main  # Run on push to the main branch
  pull_request:
    branches:
      - main  # Run on pull request targeting the main branch

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name 'Jaison'
        git config --global user.email 'jaison4577@gmail.com'
    - name: Add upstream remote
      run: git remote add upstream https://github.com/karankumarsahu/wireguard_server_test.git

    - name: Fetch upstream changes
      run: git fetch upstream

    - name: Merge changes from upstream
      run: |
        git checkout main
        git merge upstream/main --no-edit --allow-unrelated-histories || echo "Merge failed, resolving conflict..."
    - name: Resolve conflict by accepting upstream changes
      run: |
        # Discard changes in main.go from the current branch (your fork) and accept upstream's version
        git checkout upstream/main -- main.go
        git add main.go
        git commit -m "Resolved conflict by accepting upstream changes"
    - name: Push changes to fork (if changes were made)
      run: |
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

    - name: Trigger the CI/CD pipeline
      run: |
        curl -X POST -u "${{ secrets.MY_GITHUB_TOKEN }}" \
          -d '{"event_type": "sync-complete"}' \
          "https://api.github.com/repos/${{ github.repository }}/dispatches"
