name: Sync with upstream

on:
  schedule:
    - cron: "0 * * * *"  # Run every hour; adjust as needed
  push:
    branches:
      - main  # Run on push to the main branch
  pull_request:
    branches:
      - main  # Run on pull request targeting the main branch

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'Jaison'
          git config --global user.email 'jaison4577@gmail.com'

      - name: Add upstream remote
        run: git remote add upstream https://github.com/karankumarsahu/wireguard_server_test.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Attempt to merge upstream changes
        run: |
          git checkout main
          git merge upstream/main --no-edit --allow-unrelated-histories || echo "Merge conflict detected, skipping push"

      - name: Stage and commit changes (if any)
        run: |
          # Check if there were any changes
          if git diff --exit-code; then
            echo "No changes detected, skipping commit"
          else
            git add .
            git commit -m "Sync with upstream"
            git push origin main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
