name: Sync with upstream

on:
  repository_dispatch:
    types: [sync-upstream]  # Custom event type to trigger the workflow

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name 'Jaison'
        git config --global user.email 'jaison4577@gmail.com'

    - name: Add upstream remote
      run: git remote add upstream https://github.com/karankumarsahu/wireguard_server_test.git

    - name: Fetch upstream changes
      run: git fetch upstream

    - name: Merge upstream changes (preserve local commits)
      run: |
        git checkout main
        # Fetch the latest upstream changes
        git merge upstream/main --strategy=recursive -X theirs --no-edit --allow-unrelated-histories || echo "Merge conflicts, skipping changes"

    - name: Push changes to fork (if changes were made)
      run: |
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

    - name: Trigger the CI/CD pipeline
      run: |
        curl -X POST -u "${{ secrets.MY_GITHUB_TOKEN }}" \
          -d '{"event_type": "sync-complete"}' \
          "https://api.github.com/repos/${{ github.repository }}/dispatches"
